services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - ai
    networks:
      - devnet

  ai:
    build:
      context: ./ai
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - devnet

networks:
  devnet:
    driver: bridge
